#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width                    0
bspc config window_gap                      5
bspc config split_ratio                     0.50

bspc config borderless_monocle   	        true
bspc config gapless_monocle      	        true
bspc config single_monocle                  true

bspc config focus_follows_pointer 	        true
bspc config pointer_follows_focus 	        true

bspc config initial_polarity 		        first_child
bspc config automatic_scheme 		        spiral

bspc config pointer_modifier 		        control
bspc config pointer_action1 		        move
bspc config pointer_action2 		        resize_side

# Init
sh $HOME/.config/bspwm/init

# Rules
#source $HOME/.config/bspwm/rules

